from enum import Enum

class ExchangeCode(Enum):
    """
    Enumeration for different exchanges used in the Tradier API.
    """
    NYSE_MKT = "A"
    NASDAQ_BX = "B"
    NATIONAL_STOCK_EXCHANGE = "C"
    FINRA_ADF = "D"
    MARKET_INDEPENDENT = "E"
    MUTUAL_FUNDS = "F"
    INTERNATIONAL_SECURITIES_EXCHANGE = "I"
    DIRECT_EDGE_A = "J"
    DIRECT_EDGE_X = "K"
    LONG_TERM_STOCK_EXCHANGE = "L"
    CHICAGO_STOCK_EXCHANGE = "M"
    NYSE = "N"
    NYSE_ARCA = "P"
    NASDAQ_OMX = "Q"
    NASDAQ_SMALL_CAP = "S"
    NASDAQ_INT = "T"
    OTCBB = "U"
    OTC_OTHER = "V"
    CBOE = "W"
    NASDAQ_OMX_PSX = "X"
    GLOBEX = "G"
    BATS_Y_EXCHANGE = "Y"
    BATS = "Z"

    # OPRA Feeds (Options)
    NYSE_AMEX_OPTIONS = "A"
    BOX_OPTIONS_EXCHANGE = "B"
    CBOE_OPTIONS = "C"
    ISE_GEMINI = "H"
    MIAX_OPTIONS_EXCHANGE = "M"
    NYSE_ARCA_OPTIONS = "N"
    OPRA = "O"
    MIAX_PEARL = "P"
    NASDAQ_OPTIONS_MARKET = "Q"
    NASDAQ_OMX_BX_OPTIONS = "T"
    C2_OPTIONS_EXCHANGE = "W"
    NASDAQ_OMX_PHLX = "X"
    BATS_OPTIONS_MARKET = "Z"    
